### ISSUE TITLE
example figure for genCov draws UTRs inconsistently

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/GGgenome#30]
Notice that in the vignette example for genCov the UTRs for the different isoforms look odd. In the top isoform there is just one UTR feature plotted in the middle of the gene. I the second isoform the UTRs are plotted on top of and overlapping with the coding portion of the first and last exon. In the third isoform the UTRs look conventional (as expected).

**Comment by obigriffith** [comment]
Also on this figure, the coverage (y axis) should be labelled in bottom panel and the transcript models should be labeled (by ENST id?)

**Comment by zskidmor** [comment]
Yes, this is part of issue 29, it is fixed but has not been pushed yet
