### ISSUE TITLE
Does conversion of c.notation to p.notation really work as described?

### ISSUE THREAD

**Issue by obigriffith** [griffithlab/GGgenome#31]
In the vignette docs it is stated "It is recommended for amino acid change to be in p. notation however lolliplot will attempt to convert from c. notation to p.notation by subtracting the 5’ UTR transcript length from the c. coordinate, when employing this functionality the user must specify an ensembl data set via the ensembl.dataset parameter."  Isn't the c.notation at the cDNA/transcript level? Converting to p.notation would require more than just subtracting the UTR length.

**Comment by zskidmor** [comment]
@obigriffith Yes, though it was not documented fully. It subtracts the 5`utr length from the corrdinate and divides by 3 rounding to the nearest integer.

Based on our discussion this morning I will remove the documentation from the vignette and leave hidden with a warning message and add in a check to make sure there are not multiple 5` or 3` UTR regions for the same transcript ID
