### ISSUE TITLE
mutSpec Mutations per MB graph not aligning with small sample size

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/GGgenome#48]
When I use mutSpec with small sample sizes (N=7), the Mutations per MB no longer aligns with the appropriate sample and is instead squished above 6 out of the 7 samples.
![test](https://cloud.githubusercontent.com/assets/8527125/8310669/1959ae38-1997-11e5-99db-d6f2f8cc3fa5.png)

**Comment by zskidmor** [comment]
This happens when the input data frame is not properly leveled. This seems to be a common problem, I will add in a check for proper leveling and fix it for the user if its not
